#############################################################################
# Makefile for building: qmo2
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Fri Mar  9 16:30:04 2012
# Project:  qmo2.pro
# Template: subdirs
# Command: $(QMAKE) -o Makefile qmo2.pro
#############################################################################

MAKEFILE =	Makefile
QMAKE    =	qmake
DEL_FILE =    rm -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p
INSTALL_FILE= 
INSTALL_DIR = 
SUBTARGETS =	 \
		sub-qmo2 \
		sub-elems

first: all

all: Makefile $(SUBTARGETS)

qmo2/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "qmo2" || $(MKDIR) "qmo2"
	cd qmo2 && $(QMAKE) qmo2.pro -o $(MAKEFILE)
sub-qmo2: qmo2/$(MAKEFILE) FORCE
	cd qmo2 && $(MAKE) -f $(MAKEFILE)

elems/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "elems" || $(MKDIR) "elems"
	cd elems && $(QMAKE) elems.pro -o $(MAKEFILE)
sub-elems: elems/$(MAKEFILE) FORCE
	cd elems && $(MAKE) -f $(MAKEFILE)

Makefile: qmo2.pro  /usr/lib/qt-3.3/mkspecs/default/qmake.conf 
	$(QMAKE) -o Makefile qmo2.pro
qmake: qmake_all
	@$(QMAKE) -o Makefile qmo2.pro

all: $(SUBTARGETS)
qmake_all: qmo2/$(MAKEFILE) elems/$(MAKEFILE)
	 ( [ -d qmo2 ] && cd qmo2 ; grep "^qmake_all:" $(MAKEFILE) && $(MAKE) -f $(MAKEFILE) qmake_all; ) || true
	 ( [ -d elems ] && cd elems ; grep "^qmake_all:" $(MAKEFILE) && $(MAKE) -f $(MAKEFILE) qmake_all; ) || true
clean uicables mocables uiclean mocclean lexclean yaccclean : qmake_all FORCE
	 ( [ -d qmo2 ] && cd qmo2 ; $(MAKE) -f $(MAKEFILE) $@; ) || true
	 ( [ -d elems ] && cd elems ; $(MAKE) -f $(MAKEFILE) $@; ) || true
uninstall_subdirs: qmake_all FORCE
	 ( [ -d qmo2 ] && cd qmo2 ; $(MAKE) -f $(MAKEFILE) uninstall; ) || true
	 ( [ -d elems ] && cd elems ; $(MAKE) -f $(MAKEFILE) uninstall; ) || true
install_subdirs: qmake_all FORCE
	 ( [ -d qmo2 ] && cd qmo2 ; $(MAKE) -f $(MAKEFILE) install; ) || true
	 ( [ -d elems ] && cd elems ; $(MAKE) -f $(MAKEFILE) install; ) || true
distclean: qmake_all FORCE
	 ( [ -d qmo2 ] && cd qmo2 ; $(MAKE) -f $(MAKEFILE) $@; $(DEL_FILE) $(MAKEFILE); ) || true
	 ( [ -d elems ] && cd elems ; $(MAKE) -f $(MAKEFILE) $@; $(DEL_FILE) $(MAKEFILE); ) || true

install:  install_subdirs

uninstall:  uninstall_subdirs

FORCE:

