#############################################################################
# Makefile for building: qmo2
# Generated by qmake (2.01a) (Qt 4.8.0) on: Sat Mar 10 20:07:26 2012
# Project:  qmo2.pro
# Template: subdirs
# Command: /usr/bin/qmake-qt4 -o Makefile qmo2.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake-qt4
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-qmo2 \
		sub-elems

qmo2/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qmo2/ || $(MKDIR) qmo2/ 
	cd qmo2/ && $(QMAKE) /home/atu/rpm/1/proj/qmo2x/qmo2/qmo2.pro -o $(MAKEFILE)
sub-qmo2-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qmo2/ || $(MKDIR) qmo2/ 
	cd qmo2/ && $(QMAKE) /home/atu/rpm/1/proj/qmo2x/qmo2/qmo2.pro -o $(MAKEFILE)
sub-qmo2: qmo2/$(MAKEFILE) FORCE
	cd qmo2/ && $(MAKE) -f $(MAKEFILE)
sub-qmo2-make_default: qmo2/$(MAKEFILE) FORCE
	cd qmo2/ && $(MAKE) -f $(MAKEFILE) 
sub-qmo2-make_first: qmo2/$(MAKEFILE) FORCE
	cd qmo2/ && $(MAKE) -f $(MAKEFILE) first
sub-qmo2-all: qmo2/$(MAKEFILE) FORCE
	cd qmo2/ && $(MAKE) -f $(MAKEFILE) all
sub-qmo2-clean: qmo2/$(MAKEFILE) FORCE
	cd qmo2/ && $(MAKE) -f $(MAKEFILE) clean
sub-qmo2-distclean: qmo2/$(MAKEFILE) FORCE
	cd qmo2/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qmo2-install_subtargets: qmo2/$(MAKEFILE) FORCE
	cd qmo2/ && $(MAKE) -f $(MAKEFILE) install
sub-qmo2-uninstall_subtargets: qmo2/$(MAKEFILE) FORCE
	cd qmo2/ && $(MAKE) -f $(MAKEFILE) uninstall
elems/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) elems/ || $(MKDIR) elems/ 
	cd elems/ && $(QMAKE) /home/atu/rpm/1/proj/qmo2x/elems/elems.pro -o $(MAKEFILE)
sub-elems-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) elems/ || $(MKDIR) elems/ 
	cd elems/ && $(QMAKE) /home/atu/rpm/1/proj/qmo2x/elems/elems.pro -o $(MAKEFILE)
sub-elems: elems/$(MAKEFILE) FORCE
	cd elems/ && $(MAKE) -f $(MAKEFILE)
sub-elems-make_default: elems/$(MAKEFILE) FORCE
	cd elems/ && $(MAKE) -f $(MAKEFILE) 
sub-elems-make_first: elems/$(MAKEFILE) FORCE
	cd elems/ && $(MAKE) -f $(MAKEFILE) first
sub-elems-all: elems/$(MAKEFILE) FORCE
	cd elems/ && $(MAKE) -f $(MAKEFILE) all
sub-elems-clean: elems/$(MAKEFILE) FORCE
	cd elems/ && $(MAKE) -f $(MAKEFILE) clean
sub-elems-distclean: elems/$(MAKEFILE) FORCE
	cd elems/ && $(MAKE) -f $(MAKEFILE) distclean
sub-elems-install_subtargets: elems/$(MAKEFILE) FORCE
	cd elems/ && $(MAKE) -f $(MAKEFILE) install
sub-elems-uninstall_subtargets: elems/$(MAKEFILE) FORCE
	cd elems/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: qmo2.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt4/mkspecs/common/g++-base.conf \
		/usr/lib/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/lib/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile qmo2.pro
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/common/gcc-base.conf:
/usr/lib/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt4/mkspecs/common/g++-base.conf:
/usr/lib/qt4/mkspecs/common/g++-unix.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/modules/qt_phonon.pri:
/usr/lib/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/release.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile qmo2.pro

qmake_all: sub-qmo2-qmake_all sub-elems-qmake_all FORCE

make_default: sub-qmo2-make_default sub-elems-make_default FORCE
make_first: sub-qmo2-make_first sub-elems-make_first FORCE
all: sub-qmo2-all sub-elems-all FORCE
clean: sub-qmo2-clean sub-elems-clean FORCE
distclean: sub-qmo2-distclean sub-elems-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-qmo2-install_subtargets sub-elems-install_subtargets FORCE
uninstall_subtargets: sub-qmo2-uninstall_subtargets sub-elems-uninstall_subtargets FORCE

sub-qmo2-check: qmo2/$(MAKEFILE)
	cd qmo2/ && $(MAKE) -f $(MAKEFILE) check
sub-elems-check: elems/$(MAKEFILE)
	cd elems/ && $(MAKE) -f $(MAKEFILE) check
check: sub-qmo2-check sub-elems-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

